### ISSUE TITLE
Image link broken

### ISSUE THREAD

**Issue by fwestenberg** [Flamingo-tech/Open_Duco#1]
Just a small thing, the image link [here ](https://github.com/Flamingo-tech/Open_Duco/tree/main/sensors/0000-4218%20-%20Humidity%20Sensor-%20Vochtsensor/V2.0#schematic) is broken it seems.

**Comment by Flamingo-tech** [comment]
Thanks! Fixed :)

**Comment by fwestenberg** [comment]
Thanks!
